# Generated by Django 5.0.1 on 2024-01-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Данные ученика', 'verbose_name_plural': 'Данные ученика'},
        ),
    ]
